export const PER_ACRE_DEFAULTS = {
  pricePerAcre: 10000,
  avgProjectSizeAcres: 35,
  totalSAMacres: 350000,
  automationSuitablePct: 55,
  qualifiedLeadsPerBDPerYear: 600,
  leadToMeetingConvPct: 15,
  meetingToDemoConvPct: 60,
  demoToDealConvPct: 35,
  projectsPerBDPerYear: 18,
  hoursPerProject: 4,
  sessionsPerDay: 2,
  workingDaysPerMonth: 20,
  effectiveUtilisationPct: 40,
  projectsPerSpecialistPerYear: 160,
  marketCapturePct: 1,
  numPlanningSpecialists: 1,
  numBDPersonnel: 6,
  numOperations: 2,
  numFounders: 2,
  activePricingTier: 'baseline',
  perAcreProjectsY1: 25,
  perAcreProjectsY2: 60,
  perAcreProjectsY3: 120,
  perAcreProjectsY4: 200,
  perAcreProjectsY5: 350,
};

export const PRICE_TIERS = {
  entry: 5000,
  baseline: 10000,
  enterprise: 15000,
  premium: 25000,
};
